// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {siteclient} from '../models';

export function BeginDeviceAuthorization(arg1:main.DeviceAuthorizationInput):Promise<main.DeviceAuthorizationView>;

export function Checkin():Promise<main.CheckinResult>;

export function ClearConnection():Promise<void>;

export function CreateCheckoutSession(arg1:main.CheckoutSessionInput):Promise<siteclient.CheckoutSession>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeleteImageHistory(arg1:string):Promise<void>;

export function DownloadImage(arg1:string,arg2:string):Promise<main.LocalImageAssetSummary>;

export function EditImage(arg1:main.ImageEditInput):Promise<main.ImageTaskView>;

export function GenerateImage(arg1:main.ImageGenerateInput):Promise<main.ImageTaskView>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCapabilities():Promise<siteclient.ClientCapabilities>;

export function GetCheckoutSession(arg1:string):Promise<siteclient.CheckoutSession>;

export function GetConnection():Promise<main.ConnectionSummary>;

export function GetImageCapabilities():Promise<siteclient.ImageCapabilities>;

export function GetImageHistory(arg1:string):Promise<siteclient.ImageHistoryItem>;

export function GetImageHistoryAsset(arg1:string,arg2:number):Promise<siteclient.ImageHistoryAsset>;

export function GetImageTask(arg1:string):Promise<main.ImageTaskView>;

export function GetIntegrationProfiles(arg1:number):Promise<siteclient.IntegrationProfileResponse>;

export function GetToolConfigPaths(arg1:string):Promise<Record<string, string>>;

export function GetUsage():Promise<main.UsageSummary>;

export function GetUsageOverview():Promise<main.UsageOverview>;

export function ImageLibrary():Promise<Array<main.LocalImageAssetSummary>>;

export function IntegrateToolConfig(arg1:main.ToolConfigInput):Promise<main.ToolConfigResult>;

export function LaunchTool(arg1:string):Promise<main.ToolLaunchResult>;

export function ListAPIKeys():Promise<Array<main.APIKeySummary>>;

export function ListDevices():Promise<Array<main.DeviceSummary>>;

export function ListImageHistory(arg1:main.ImageHistoryQueryInput):Promise<siteclient.ImageHistoryPage>;

export function ListImageTasks():Promise<Array<main.ImageTaskSummary>>;

export function LogoutDevice():Promise<void>;

export function MarkImageTaskAssetsDownloaded(arg1:string):Promise<void>;

export function OpenCheckout(arg1:string):Promise<void>;

export function OpenDeviceVerification(arg1:string):Promise<void>;

export function OpenKeysPage():Promise<void>;

export function PickImageFiles(arg1:boolean):Promise<Array<main.ImageFileHandle>>;

export function PollDeviceAuthorization(arg1:string):Promise<main.DeviceAuthorizationStatus>;

export function ProbeConnection():Promise<main.ProbeResult>;

export function RestoreToolConfig(arg1:main.ToolConfigRestoreInput):Promise<main.ToolConfigRestoreResult>;

export function RevokeDevice(arg1:string):Promise<void>;

export function SaveConnection(arg1:main.ConnectionInput):Promise<main.ConnectionSummary>;

export function SelectAPIKey(arg1:number):Promise<main.APIKeySelectionResult>;

export function SelectAPIKeyForPurpose(arg1:string,arg2:number):Promise<main.APIKeySelectionResult>;
