// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginDeviceAuthorization(arg1) {
  return window['go']['main']['App']['BeginDeviceAuthorization'](arg1);
}

export function Checkin() {
  return window['go']['main']['App']['Checkin']();
}

export function ClearConnection() {
  return window['go']['main']['App']['ClearConnection']();
}

export function CreateCheckoutSession(arg1) {
  return window['go']['main']['App']['CreateCheckoutSession'](arg1);
}

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function DeleteImageHistory(arg1) {
  return window['go']['main']['App']['DeleteImageHistory'](arg1);
}

export function DownloadImage(arg1, arg2) {
  return window['go']['main']['App']['DownloadImage'](arg1, arg2);
}

export function EditImage(arg1) {
  return window['go']['main']['App']['EditImage'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetCheckoutSession(arg1) {
  return window['go']['main']['App']['GetCheckoutSession'](arg1);
}

export function GetConnection() {
  return window['go']['main']['App']['GetConnection']();
}

export function GetImageCapabilities() {
  return window['go']['main']['App']['GetImageCapabilities']();
}

export function GetImageHistory(arg1) {
  return window['go']['main']['App']['GetImageHistory'](arg1);
}

export function GetImageHistoryAsset(arg1, arg2) {
  return window['go']['main']['App']['GetImageHistoryAsset'](arg1, arg2);
}

export function GetImageTask(arg1) {
  return window['go']['main']['App']['GetImageTask'](arg1);
}

export function GetIntegrationProfiles(arg1) {
  return window['go']['main']['App']['GetIntegrationProfiles'](arg1);
}

export function GetToolConfigPaths(arg1) {
  return window['go']['main']['App']['GetToolConfigPaths'](arg1);
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function GetUsageOverview() {
  return window['go']['main']['App']['GetUsageOverview']();
}

export function ImageLibrary() {
  return window['go']['main']['App']['ImageLibrary']();
}

export function IntegrateToolConfig(arg1) {
  return window['go']['main']['App']['IntegrateToolConfig'](arg1);
}

export function LaunchTool(arg1) {
  return window['go']['main']['App']['LaunchTool'](arg1);
}

export function ListAPIKeys() {
  return window['go']['main']['App']['ListAPIKeys']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListImageHistory(arg1) {
  return window['go']['main']['App']['ListImageHistory'](arg1);
}

export function ListImageTasks() {
  return window['go']['main']['App']['ListImageTasks']();
}

export function LogoutDevice() {
  return window['go']['main']['App']['LogoutDevice']();
}

export function MarkImageTaskAssetsDownloaded(arg1) {
  return window['go']['main']['App']['MarkImageTaskAssetsDownloaded'](arg1);
}

export function OpenCheckout(arg1) {
  return window['go']['main']['App']['OpenCheckout'](arg1);
}

export function OpenDeviceVerification(arg1) {
  return window['go']['main']['App']['OpenDeviceVerification'](arg1);
}

export function OpenKeysPage() {
  return window['go']['main']['App']['OpenKeysPage']();
}

export function PickImageFiles(arg1) {
  return window['go']['main']['App']['PickImageFiles'](arg1);
}

export function PollDeviceAuthorization(arg1) {
  return window['go']['main']['App']['PollDeviceAuthorization'](arg1);
}

export function ProbeConnection() {
  return window['go']['main']['App']['ProbeConnection']();
}

export function RestoreToolConfig(arg1) {
  return window['go']['main']['App']['RestoreToolConfig'](arg1);
}

export function RevokeDevice(arg1) {
  return window['go']['main']['App']['RevokeDevice'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SelectAPIKey(arg1) {
  return window['go']['main']['App']['SelectAPIKey'](arg1);
}

export function SelectAPIKeyForPurpose(arg1, arg2) {
  return window['go']['main']['App']['SelectAPIKeyForPurpose'](arg1, arg2);
}
