//go:build embed

package web

import (
	"bytes"
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"encoding/xml"
	"html"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

type injectedSiteSEO struct {
	SiteName     string `json:"site_name"`
	SiteLogo     string `json:"site_logo"`
	SiteSubtitle string `json:"site_subtitle"`
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		if tryServeSEOFile(c, path) {
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		requestETag := requestScopedETag(cached.ETag, c)
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == requestETag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)
		content = injectRequestSEO(content, c)

		c.Header("ETag", requestETag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)
	content = injectRequestSEO(content, c)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", requestScopedETag(cached.ETag, c))
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Replace generic SEO tags with public site settings so crawlers and link previews
	// see the configured brand before the SPA boots.
	result = injectSiteSEO(result, settingsJSON)

	return result
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(doc, settingsJSON []byte) []byte {
	var cfg injectedSiteSEO
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return doc
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(doc, []byte("<title>"))
	titleEnd := bytes.Index(doc, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return doc
	}

	newTitle := []byte("<title>" + html.EscapeString(siteSEOTitle(cfg.SiteName)) + "</title>")
	var buf bytes.Buffer
	buf.Write(doc[:titleStart])
	buf.Write(newTitle)
	buf.Write(doc[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func injectSiteSEO(doc, settingsJSON []byte) []byte {
	var cfg injectedSiteSEO
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return doc
	}
	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		siteName = "Sub2API"
	}
	description := siteSEODescription(cfg.SiteSubtitle)
	image := strings.TrimSpace(cfg.SiteLogo)
	if image == "" {
		image = "/logo.png"
	}

	result := injectSiteTitle(doc, settingsJSON)
	title := siteSEOTitle(siteName)
	result = replaceMetaContent(result, `name`, `description`, description)
	result = replaceMetaContent(result, `property`, `og:site_name`, siteName)
	result = replaceMetaContent(result, `property`, `og:title`, title)
	result = replaceMetaContent(result, `property`, `og:description`, description)
	result = replaceMetaContent(result, `property`, `og:image`, image)
	result = replaceMetaContent(result, `name`, `twitter:title`, title)
	result = replaceMetaContent(result, `name`, `twitter:description`, description)
	return result
}

func siteSEOTitle(siteName string) string {
	name := strings.TrimSpace(siteName)
	if name == "" {
		name = "Sub2API"
	}
	return name + " - AI API Gateway"
}

func siteSEODescription(siteSubtitle string) string {
	if subtitle := strings.TrimSpace(siteSubtitle); subtitle != "" {
		return subtitle
	}
	return "Sub2API is an AI API gateway for unified model access, account routing, usage billing, and API key management."
}

func replaceMetaContent(doc []byte, attrName, attrValue, content string) []byte {
	marker := []byte(`<meta ` + attrName + `="` + attrValue + `"`)
	start := bytes.Index(doc, marker)
	if start == -1 {
		return doc
	}
	tagEndRel := bytes.IndexByte(doc[start:], '>')
	if tagEndRel == -1 {
		return doc
	}
	tagEnd := start + tagEndRel
	contentMarker := []byte(`content="`)
	contentStartRel := bytes.Index(doc[start:tagEnd], contentMarker)
	if contentStartRel == -1 {
		return doc
	}
	valueStart := start + contentStartRel + len(contentMarker)
	valueEndRel := bytes.IndexByte(doc[valueStart:tagEnd], '"')
	if valueEndRel == -1 {
		return doc
	}
	valueEnd := valueStart + valueEndRel

	var buf bytes.Buffer
	buf.Write(doc[:valueStart])
	buf.WriteString(html.EscapeString(content))
	buf.Write(doc[valueEnd:])
	return buf.Bytes()
}

func replaceCanonicalHref(doc []byte, href string) []byte {
	marker := []byte(`<link rel="canonical"`)
	start := bytes.Index(doc, marker)
	if start == -1 {
		return doc
	}
	tagEndRel := bytes.IndexByte(doc[start:], '>')
	if tagEndRel == -1 {
		return doc
	}
	tagEnd := start + tagEndRel
	hrefMarker := []byte(`href="`)
	hrefStartRel := bytes.Index(doc[start:tagEnd], hrefMarker)
	if hrefStartRel == -1 {
		return doc
	}
	valueStart := start + hrefStartRel + len(hrefMarker)
	valueEndRel := bytes.IndexByte(doc[valueStart:tagEnd], '"')
	if valueEndRel == -1 {
		return doc
	}
	valueEnd := valueStart + valueEndRel

	var buf bytes.Buffer
	buf.Write(doc[:valueStart])
	buf.WriteString(html.EscapeString(href))
	buf.Write(doc[valueEnd:])
	return buf.Bytes()
}

func injectRequestSEO(doc []byte, c *gin.Context) []byte {
	robots := "noindex, nofollow"
	if isIndexablePublicPath(c.Request.URL.Path) {
		robots = "index, follow"
	}
	result := replaceMetaContent(doc, `name`, `robots`, robots)
	return replaceCanonicalHref(result, canonicalURL(c))
}

func isIndexablePublicPath(path string) bool {
	trimmed := strings.TrimRight(strings.TrimSpace(path), "/")
	return trimmed == "" || trimmed == "/home" || strings.HasPrefix(trimmed, "/legal/")
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func tryServeSEOFile(c *gin.Context, path string) bool {
	switch strings.TrimSpace(path) {
	case "/robots.txt":
		serveRobotsTXT(c)
		return true
	case "/sitemap.xml":
		serveSitemapXML(c)
		return true
	default:
		return false
	}
}

func serveRobotsTXT(c *gin.Context) {
	base := requestBaseURL(c)
	body := "User-agent: *\n" +
		"Allow: /$\n" +
		"Allow: /home\n" +
		"Allow: /legal/\n" +
		"Disallow: /admin/\n" +
		"Disallow: /auth/\n" +
		"Disallow: /dashboard\n" +
		"Disallow: /keys\n" +
		"Disallow: /usage\n" +
		"Disallow: /profile\n" +
		"Disallow: /payment/\n" +
		"Disallow: /purchase\n" +
		"Disallow: /orders\n" +
		"Sitemap: " + base + "/sitemap.xml\n"
	c.Data(http.StatusOK, "text/plain; charset=utf-8", []byte(body))
	c.Abort()
}

type sitemapURLSet struct {
	XMLName xml.Name     `xml:"urlset"`
	Xmlns   string       `xml:"xmlns,attr"`
	URLs    []sitemapURL `xml:"url"`
}

type sitemapURL struct {
	Loc        string `xml:"loc"`
	ChangeFreq string `xml:"changefreq,omitempty"`
	Priority   string `xml:"priority,omitempty"`
}

func serveSitemapXML(c *gin.Context) {
	base := requestBaseURL(c)
	urlset := sitemapURLSet{
		Xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9",
		URLs: []sitemapURL{
			{Loc: base + "/home", ChangeFreq: "weekly", Priority: "1.0"},
		},
	}
	content, err := xml.MarshalIndent(urlset, "", "  ")
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to generate sitemap")
		c.Abort()
		return
	}
	body := append([]byte(xml.Header), content...)
	c.Data(http.StatusOK, "application/xml; charset=utf-8", body)
	c.Abort()
}

func canonicalURL(c *gin.Context) string {
	path := strings.TrimSpace(c.Request.URL.Path)
	if path == "" || path == "/" {
		path = "/home"
	}
	return requestBaseURL(c) + path
}

func requestScopedETag(baseETag string, c *gin.Context) string {
	cleanBase := strings.Trim(baseETag, `"`)
	if cleanBase == "" {
		cleanBase = "html"
	}
	seed := canonicalURL(c) + "|" + c.Request.URL.Path
	if isIndexablePublicPath(c.Request.URL.Path) {
		seed += "|index"
	} else {
		seed += "|noindex"
	}
	sum := sha256.Sum256([]byte(seed))
	return `"` + cleanBase + "-" + hex.EncodeToString(sum[:8]) + `"`
}

func requestBaseURL(c *gin.Context) string {
	scheme := c.GetHeader("X-Forwarded-Proto")
	if scheme == "" {
		scheme = "http"
		if c.Request.TLS != nil {
			scheme = "https"
		}
	}
	host := c.GetHeader("X-Forwarded-Host")
	if host == "" {
		host = c.Request.Host
	}
	if host == "" {
		host = "localhost"
	}
	return strings.TrimRight(scheme+"://"+host, "/")
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		strings.HasPrefix(trimmed, "/images/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
