//go:build embed

package web

import (
	"bytes"
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"encoding/xml"
	"html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

type injectedSiteSEO struct {
	SiteName                string                   `json:"site_name"`
	SiteLogo                string                   `json:"site_logo"`
	SiteSubtitle            string                   `json:"site_subtitle"`
	CustomMenuItems         []injectedCustomMenuItem `json:"custom_menu_items"`
	LoginAgreementDocuments []injectedLegalDocument  `json:"login_agreement_documents"`
}

type injectedCustomMenuItem struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	URL        string `json:"url"`
	PageSlug   string `json:"page_slug"`
	Visibility string `json:"visibility"`
	SortOrder  int    `json:"sort_order"`
}

type injectedLegalDocument struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		if s.tryServeSEOFile(c, path) {
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		requestETag := requestScopedETag(cached.ETag, c)
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == requestETag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)
		content = injectRequestSEO(content, c, cached.Settings)

		c.Header("ETag", requestETag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)
	content = injectRequestSEO(content, c, settingsJSON)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", requestScopedETag(cached.ETag, c))
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Replace generic SEO tags with public site settings so crawlers and link previews
	// see the configured brand before the SPA boots.
	result = injectSiteSEO(result, settingsJSON)

	return result
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(doc, settingsJSON []byte) []byte {
	var cfg injectedSiteSEO
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return doc
	}

	return replaceHTMLTitle(doc, siteSEOTitle(cfg.SiteName))
}

func replaceHTMLTitle(doc []byte, title string) []byte {
	titleStart := bytes.Index(doc, []byte("<title>"))
	titleEnd := bytes.Index(doc, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return doc
	}

	newTitle := []byte("<title>" + html.EscapeString(title) + "</title>")
	var buf bytes.Buffer
	buf.Write(doc[:titleStart])
	buf.Write(newTitle)
	buf.Write(doc[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func injectSiteSEO(doc, settingsJSON []byte) []byte {
	var cfg injectedSiteSEO
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return doc
	}
	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		siteName = "Sub2API"
	}
	description := siteSEODescription(cfg.SiteSubtitle)
	image := strings.TrimSpace(cfg.SiteLogo)
	if image == "" {
		image = "/logo.png"
	}

	result := injectSiteTitle(doc, settingsJSON)
	title := siteSEOTitle(siteName)
	result = replaceMetaContent(result, `name`, `description`, description)
	result = replaceMetaContent(result, `property`, `og:site_name`, siteName)
	result = replaceMetaContent(result, `property`, `og:title`, title)
	result = replaceMetaContent(result, `property`, `og:description`, description)
	result = replaceMetaContent(result, `property`, `og:image`, image)
	result = replaceMetaContent(result, `name`, `twitter:title`, title)
	result = replaceMetaContent(result, `name`, `twitter:description`, description)
	return replaceFavicon(result, image)
}

func siteSEOTitle(siteName string) string {
	name := strings.TrimSpace(siteName)
	if name == "" {
		name = "Sub2API"
	}
	return name + " - AI API Gateway"
}

func siteSEODescription(siteSubtitle string) string {
	if subtitle := strings.TrimSpace(siteSubtitle); subtitle != "" {
		return subtitle
	}
	return "Sub2API is an AI API gateway for unified model access, account routing, usage billing, and API key management."
}

func replaceMetaContent(doc []byte, attrName, attrValue, content string) []byte {
	marker := []byte(`<meta ` + attrName + `="` + attrValue + `"`)
	start := bytes.Index(doc, marker)
	if start == -1 {
		return doc
	}
	tagEndRel := bytes.IndexByte(doc[start:], '>')
	if tagEndRel == -1 {
		return doc
	}
	tagEnd := start + tagEndRel
	contentMarker := []byte(`content="`)
	contentStartRel := bytes.Index(doc[start:tagEnd], contentMarker)
	if contentStartRel == -1 {
		return doc
	}
	valueStart := start + contentStartRel + len(contentMarker)
	valueEndRel := bytes.IndexByte(doc[valueStart:tagEnd], '"')
	if valueEndRel == -1 {
		return doc
	}
	valueEnd := valueStart + valueEndRel

	var buf bytes.Buffer
	buf.Write(doc[:valueStart])
	buf.WriteString(html.EscapeString(content))
	buf.Write(doc[valueEnd:])
	return buf.Bytes()
}

func replaceFavicon(doc []byte, href string) []byte {
	marker := []byte(`<link rel="icon"`)
	start := bytes.Index(doc, marker)
	if start == -1 {
		return doc
	}
	tagEndRel := bytes.IndexByte(doc[start:], '>')
	if tagEndRel == -1 {
		return doc
	}
	tagEnd := start + tagEndRel
	result := replaceTagAttrValue(doc, start, tagEnd, "href", href)
	start = bytes.Index(result, marker)
	if start == -1 {
		return result
	}
	tagEndRel = bytes.IndexByte(result[start:], '>')
	if tagEndRel == -1 {
		return result
	}
	tagEnd = start + tagEndRel
	return replaceTagAttrValue(result, start, tagEnd, "type", faviconMimeType(href))
}

func replaceTagAttrValue(doc []byte, tagStart, tagEnd int, attrName, value string) []byte {
	attrMarker := []byte(attrName + `="`)
	attrStartRel := bytes.Index(doc[tagStart:tagEnd], attrMarker)
	if attrStartRel == -1 {
		return doc
	}
	valueStart := tagStart + attrStartRel + len(attrMarker)
	valueEndRel := bytes.IndexByte(doc[valueStart:tagEnd], '"')
	if valueEndRel == -1 {
		return doc
	}
	valueEnd := valueStart + valueEndRel

	var buf bytes.Buffer
	buf.Write(doc[:valueStart])
	buf.WriteString(html.EscapeString(value))
	buf.Write(doc[valueEnd:])
	return buf.Bytes()
}

func faviconMimeType(href string) string {
	normalized := strings.ToLower(strings.TrimSpace(href))
	if strings.HasPrefix(normalized, "data:image/svg+xml") {
		return "image/svg+xml"
	}
	if strings.HasPrefix(normalized, "data:image/jpeg") || strings.HasPrefix(normalized, "data:image/jpg") {
		return "image/jpeg"
	}
	if strings.HasPrefix(normalized, "data:image/webp") {
		return "image/webp"
	}
	if strings.HasPrefix(normalized, "data:image/x-icon") || strings.HasPrefix(normalized, "data:image/vnd.microsoft.icon") {
		return "image/x-icon"
	}

	path := normalized
	if index := strings.IndexAny(path, "?#"); index >= 0 {
		path = path[:index]
	}
	if strings.HasSuffix(path, ".svg") {
		return "image/svg+xml"
	}
	if strings.HasSuffix(path, ".jpg") || strings.HasSuffix(path, ".jpeg") {
		return "image/jpeg"
	}
	if strings.HasSuffix(path, ".webp") {
		return "image/webp"
	}
	if strings.HasSuffix(path, ".ico") {
		return "image/x-icon"
	}
	return "image/png"
}

func replaceCanonicalHref(doc []byte, href string) []byte {
	marker := []byte(`<link rel="canonical"`)
	start := bytes.Index(doc, marker)
	if start == -1 {
		return doc
	}
	tagEndRel := bytes.IndexByte(doc[start:], '>')
	if tagEndRel == -1 {
		return doc
	}
	tagEnd := start + tagEndRel
	hrefMarker := []byte(`href="`)
	hrefStartRel := bytes.Index(doc[start:tagEnd], hrefMarker)
	if hrefStartRel == -1 {
		return doc
	}
	valueStart := start + hrefStartRel + len(hrefMarker)
	valueEndRel := bytes.IndexByte(doc[valueStart:tagEnd], '"')
	if valueEndRel == -1 {
		return doc
	}
	valueEnd := valueStart + valueEndRel

	var buf bytes.Buffer
	buf.Write(doc[:valueStart])
	buf.WriteString(html.EscapeString(href))
	buf.Write(doc[valueEnd:])
	return buf.Bytes()
}

func injectRequestSEO(doc []byte, c *gin.Context, settingsJSON []byte) []byte {
	pageTitle, description, indexable := requestSEO(c.Request.URL.Path, settingsJSON)
	robots := "noindex, nofollow"
	if indexable {
		robots = "index, follow"
	}
	result := replaceHTMLTitle(doc, pageTitle)
	result = replaceMetaContent(result, `name`, `description`, description)
	result = replaceMetaContent(result, `name`, `robots`, robots)
	result = replaceMetaContent(result, `property`, `og:title`, pageTitle)
	result = replaceMetaContent(result, `property`, `og:description`, description)
	result = replaceMetaContent(result, `name`, `twitter:title`, pageTitle)
	result = replaceMetaContent(result, `name`, `twitter:description`, description)
	return replaceCanonicalHref(result, canonicalURL(c))
}

func isIndexablePublicPath(path string, settingsJSON ...[]byte) bool {
	_, _, indexable := requestSEO(path, firstSettingsJSON(settingsJSON...))
	return indexable
}

func requestSEO(path string, settingsJSON []byte) (string, string, bool) {
	cfg := parseInjectedSiteSEO(settingsJSON)
	siteName := normalizedSiteName(cfg.SiteName)
	description := siteSEODescription(cfg.SiteSubtitle)
	title := siteSEOTitle(siteName)
	trimmed := strings.TrimRight(strings.TrimSpace(path), "/")
	if trimmed == "" || trimmed == "/home" {
		return title, description, true
	}
	if id, ok := strings.CutPrefix(trimmed, "/custom/"); ok {
		id = cleanURLPathID(id)
		if item, found := findPublicCustomMenuItem(cfg.CustomMenuItems, id); found {
			return item.Label + " - " + siteName, description, true
		}
		return title, description, false
	}
	if id, ok := strings.CutPrefix(trimmed, "/legal/"); ok {
		id = cleanURLPathID(id)
		if doc, found := findLegalDocument(cfg.LoginAgreementDocuments, id); found {
			return doc.Title + " - " + siteName, description, true
		}
		return title, description, true
	}
	return title, description, false
}

func cleanURLPathID(id string) string {
	decoded, err := url.PathUnescape(strings.TrimSpace(id))
	if err != nil {
		return strings.TrimSpace(id)
	}
	return strings.TrimSpace(decoded)
}

func firstSettingsJSON(values ...[]byte) []byte {
	for _, value := range values {
		if len(value) > 0 {
			return value
		}
	}
	return nil
}

func parseInjectedSiteSEO(settingsJSON []byte) injectedSiteSEO {
	var cfg injectedSiteSEO
	if len(settingsJSON) > 0 {
		_ = json.Unmarshal(settingsJSON, &cfg)
	}
	return cfg
}

func normalizedSiteName(siteName string) string {
	name := strings.TrimSpace(siteName)
	if name == "" {
		return "Sub2API"
	}
	return name
}

func findPublicCustomMenuItem(items []injectedCustomMenuItem, id string) (injectedCustomMenuItem, bool) {
	id = strings.TrimSpace(id)
	for _, item := range items {
		if strings.TrimSpace(item.ID) == id && strings.TrimSpace(item.Label) != "" && item.Visibility != "admin" {
			return item, true
		}
	}
	return injectedCustomMenuItem{}, false
}

func findLegalDocument(items []injectedLegalDocument, id string) (injectedLegalDocument, bool) {
	id = strings.TrimSpace(id)
	for _, item := range items {
		if strings.TrimSpace(item.ID) == id && strings.TrimSpace(item.Title) != "" {
			return item, true
		}
	}
	return injectedLegalDocument{}, false
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) tryServeSEOFile(c *gin.Context, path string) bool {
	switch strings.TrimSpace(path) {
	case "/robots.txt":
		serveRobotsTXT(c, s.loadSettingsJSON(c))
		return true
	case "/sitemap.xml":
		serveSitemapXML(c, s.loadSettingsJSON(c))
		return true
	default:
		return false
	}
}

func (s *FrontendServer) loadSettingsJSON(c *gin.Context) []byte {
	if s == nil || s.settings == nil {
		return nil
	}
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()
	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		return nil
	}
	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		return nil
	}
	return settingsJSON
}

func tryServeSEOFile(c *gin.Context, path string) bool {
	switch strings.TrimSpace(path) {
	case "/robots.txt":
		serveRobotsTXT(c, nil)
		return true
	case "/sitemap.xml":
		serveSitemapXML(c, nil)
		return true
	default:
		return false
	}
}

func serveRobotsTXT(c *gin.Context, settingsJSON []byte) {
	base := requestBaseURL(c)
	cfg := parseInjectedSiteSEO(settingsJSON)
	var builder strings.Builder
	builder.WriteString("User-agent: *\n")
	builder.WriteString(
		"Allow: /$\n" +
			"Allow: /home\n" +
			"Allow: /legal/\n",
	)
	for _, item := range cfg.CustomMenuItems {
		if strings.TrimSpace(item.ID) == "" || item.Visibility == "admin" {
			continue
		}
		builder.WriteString("Allow: /custom/")
		builder.WriteString(url.PathEscape(strings.TrimSpace(item.ID)))
		builder.WriteByte('\n')
	}
	builder.WriteString(
		"Disallow: /custom/\n" +
			"Disallow: /admin/\n" +
			"Disallow: /auth/\n" +
			"Disallow: /dashboard\n" +
			"Disallow: /keys\n" +
			"Disallow: /usage\n" +
			"Disallow: /profile\n" +
			"Disallow: /payment/\n" +
			"Disallow: /purchase\n" +
			"Disallow: /orders\n" +
			"Sitemap: " + base + "/sitemap.xml\n",
	)
	c.Data(http.StatusOK, "text/plain; charset=utf-8", []byte(builder.String()))
	c.Abort()
}

type sitemapURLSet struct {
	XMLName xml.Name     `xml:"urlset"`
	Xmlns   string       `xml:"xmlns,attr"`
	URLs    []sitemapURL `xml:"url"`
}

type sitemapURL struct {
	Loc        string `xml:"loc"`
	ChangeFreq string `xml:"changefreq,omitempty"`
	Priority   string `xml:"priority,omitempty"`
}

func serveSitemapXML(c *gin.Context, settingsJSON []byte) {
	base := requestBaseURL(c)
	urls := []sitemapURL{
		{Loc: base + "/home", ChangeFreq: "weekly", Priority: "1.0"},
	}
	cfg := parseInjectedSiteSEO(settingsJSON)
	for _, item := range cfg.CustomMenuItems {
		if strings.TrimSpace(item.ID) == "" || item.Visibility == "admin" {
			continue
		}
		urls = append(urls, sitemapURL{
			Loc:        base + "/custom/" + url.PathEscape(strings.TrimSpace(item.ID)),
			ChangeFreq: "weekly",
			Priority:   "0.8",
		})
	}
	for _, doc := range cfg.LoginAgreementDocuments {
		if strings.TrimSpace(doc.ID) == "" || strings.TrimSpace(doc.Title) == "" {
			continue
		}
		urls = append(urls, sitemapURL{
			Loc:        base + "/legal/" + url.PathEscape(strings.TrimSpace(doc.ID)),
			ChangeFreq: "monthly",
			Priority:   "0.6",
		})
	}
	urlset := sitemapURLSet{
		Xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9",
		URLs:  urls,
	}
	content, err := xml.MarshalIndent(urlset, "", "  ")
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to generate sitemap")
		c.Abort()
		return
	}
	body := append([]byte(xml.Header), content...)
	c.Data(http.StatusOK, "application/xml; charset=utf-8", body)
	c.Abort()
}

func canonicalURL(c *gin.Context) string {
	path := strings.TrimSpace(c.Request.URL.Path)
	if path == "" || path == "/" {
		path = "/home"
	}
	return requestBaseURL(c) + path
}

func requestScopedETag(baseETag string, c *gin.Context) string {
	cleanBase := strings.Trim(baseETag, `"`)
	if cleanBase == "" {
		cleanBase = "html"
	}
	seed := canonicalURL(c) + "|" + c.Request.URL.Path
	if isIndexablePublicPath(c.Request.URL.Path) {
		seed += "|index"
	} else {
		seed += "|noindex"
	}
	sum := sha256.Sum256([]byte(seed))
	return `"` + cleanBase + "-" + hex.EncodeToString(sum[:8]) + `"`
}

func requestBaseURL(c *gin.Context) string {
	scheme := c.GetHeader("X-Forwarded-Proto")
	if scheme == "" {
		scheme = "http"
		if c.Request.TLS != nil {
			scheme = "https"
		}
	}
	host := c.GetHeader("X-Forwarded-Host")
	if host == "" {
		host = c.Request.Host
	}
	if host == "" {
		host = "localhost"
	}
	return strings.TrimRight(scheme+"://"+host, "/")
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		strings.HasPrefix(trimmed, "/images/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
